# Tomcat
server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  port: 8080

# 系统自定义全局配置，可根据实际需要扩展使用
global:
  upload-location: /Users/zhouchenglin/dev/dp-boot/ #文件上传目录
  upload-mapping: /upload/ #文件上传目录访问路径

spring:
  # 环境 dev:开发环境|test:测试环境|prod:生成环境
  profiles:
    active: sit
  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
  mvc:
    static-path-pattern: /static/**
  resources: # 指定静态资源的路径
    static-locations: classpath:/static/

# Mybatis配置
mybatis:
  configLocation: classpath:mybatis.xml
  mapper-locations: classpath*:net/chenlin/dp/**/mapper/*.xml
